#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE redmine_34;
    CREATE DATABASE redmine_51;
    CREATE DATABASE redmine_60;
    GRANT ALL PRIVILEGES ON DATABASE redmine_34 TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE redmine_51 TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE redmine_60 TO $POSTGRES_USER;
EOSQL
